# Generated by Django 4.1.7 on 2023-02-25 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('score', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('question2', models.CharField(max_length=200, null=True)),
                ('question3', models.CharField(max_length=200, null=True)),
                ('question4', models.CharField(max_length=200, null=True)),
                ('question5', models.CharField(max_length=200, null=True)),
                ('question6', models.CharField(max_length=200, null=True)),
                ('question7', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('ans2', models.CharField(max_length=200, null=True)),
                ('ans3', models.CharField(max_length=200, null=True)),
                ('ans4', models.CharField(max_length=200, null=True)),
                ('ans5', models.CharField(max_length=200, null=True)),
                ('ans6', models.CharField(max_length=200, null=True)),
                ('ans7', models.CharField(max_length=200, null=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
